spring:
  #数据源配置
  data:
    mongodb:
      # 主机地址
      host: 192.168.3.33
      # 数据库
      database: article
      # 默认端口是27017
      port: 27017
      # 也可以使用uri连接
      # uri: mongodb://192.168.3.33:27017/article
